import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const staleProductSlugs = [
  "p250",
  "p500",
  "p750",
  "p1000",
  "p1500",
  "p2000",
  "cooling-system",
  "frequency-converter",
  "crucible",
  "link",
];

const products = [
  // ========== کوره‌ها ==========
  {
    slug: "melting-furnace",
    name: "کوره القایی ذوب",
    category: "MELTING_FURNACE" as const,
    description:
      "کوره‌های القایی ذوب , ساخت شرکت کوره القایی پارسیان پرتوالوند با طراحی اینورتر رزونانس سری و موازی، ذوب تمیز و بدون آلودگی فلزات آهنی و غیرآهنی (استیل, فولاد، چدن،آلومینیوم, برنج و مس) رو با راندمان بالا و کنترل دقیق دما فراهم می‌کنند. این روش یکی از مفیدترین و تمیزترین روش‌های گرمایش بدون تماس مواد است و باعث ایجاد ناخالصی یا آلودگی در ذوب نمی‌شود. در طراحی سیستم اینورتر رزونانس سری و موازی، انتخاب خازن مناسب بر اساس فرکانس رزونانس، توان خروجی، ضریب قدرت، کیفیت و کارایی کوره بسیار مهم است. این خط تولید از ظرفیت‌های کوچک کارگاهی تا واحدهای صنعتی بزرگ رو پوشش می دهد",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [
      {
        powerKw: 75,
        frequencyHzMin: 1700,
        frequencyHzMax: 1800,
        ironKgHr: 55,
        steelKgHr: 50,
        bronzeKgHr: 80,
      },
      {
        powerKw: 100,
        frequencyHzMin: 1700,
        frequencyHzMax: 1800,
        ironKgHr: 120,
        steelKgHr: 110,
        bronzeKgHr: 190,
      },
      {
        powerKw: 150,
        frequencyHzMin: 1500,
        frequencyHzMax: 1700,
        ironKgHr: 220,
        steelKgHr: 200,
        bronzeKgHr: 350,
      },
      {
        powerKw: 250,
        frequencyHzMin: 1500,
        frequencyHzMax: 1700,
        ironKgHr: 440,
        steelKgHr: 400,
        bronzeKgHr: 700,
      },
      {
        powerKw: 350,
        frequencyHzMin: 1300,
        frequencyHzMax: 1500,
        ironKgHr: 600,
        steelKgHr: 540,
        bronzeKgHr: 900,
      },
      {
        powerKw: 500,
        frequencyHzMin: 1300,
        frequencyHzMax: 1500,
        ironKgHr: 900,
        steelKgHr: 820,
        bronzeKgHr: 1400,
      },
      {
        powerKw: 600,
        frequencyHzMin: 1300,
        frequencyHzMax: 1500,
        ironKgHr: 1100,
        steelKgHr: 1000,
        bronzeKgHr: 1800,
      },
      {
        powerKw: 900,
        frequencyHzMin: 900,
        frequencyHzMax: 1200,
        ironKgHr: 1800,
        steelKgHr: 1650,
        bronzeKgHr: 3000,
      },
      {
        powerKw: 1200,
        frequencyHzMin: 900,
        frequencyHzMax: 1200,
        ironKgHr: 2400,
        steelKgHr: 2100,
        bronzeKgHr: 3600,
      },
      {
        powerKw: 1800,
        frequencyHzMin: 600,
        frequencyHzMax: 800,
        ironKgHr: 3600,
        steelKgHr: 3200,
        bronzeKgHr: 4500,
      },
      {
        powerKw: 2000,
        frequencyHzMin: 600,
        frequencyHzMax: 800,
        ironKgHr: 4000,
        steelKgHr: 3500,
        bronzeKgHr: 6200,
      },
      {
        powerKw: 2500,
        frequencyHzMin: 600,
        frequencyHzMax: 800,
        ironKgHr: 5000,
        steelKgHr: 4600,
        bronzeKgHr: 7600,
      },
    ],
    components: [
      {
        title: "سیستم خنک‌کننده",
        description:
          "به‌صورت مدار بسته و هوشمند طراحی شده تا دمای آب کویل بوته، تابلوی مبدل فرکانس و بانک خازن رو به‌طور دقیق کنترل کند",
      },
      {
        title: "سیستم مبدل فرکانس",
        description:
          "تابلو مبدل فرکانس مجهز به PLC و HMI برای کنترل دقیق و ساده‌ی تمام بخش‌های کوره.",
      },
      {
        title: "بوته",
        description:
          "در سه نوع اصلی عرضه می‌شود: بدنه آلومینیومی، بدنه فولادی (یوک) و بدنه استیل",
      },
      {
        title: "لینک",
        description:
          "لینک‌های قدرت و اتصالات با طراحی استاندارد و کیفیت بالا تولید می‌شوند .",
      },
      {
        title: "قطعات و تجهیزات جانبی",
        description:
          "شامل قطعات مصرفی و کنترلی مثل تریستور، مقاومت، خازن و برد الکترونیکی.",
      },
    ],
    images: [
      "/images/products/melting-furnace-1.webp",
      "/images/products/melting-furnace-2.webp",
      "/images/products/melting-furnace-3.webp",
      "/images/products/melting-furnace-4.webp",
      "/images/products/melting-furnace-5.webp",
      "/images/products/melting-furnace-6.webp",
      "/images/products/melting-furnace-7.webp",
    ],
    featured: true,
    order: 1,
  },
  {
    slug: "forging-furnace",
    name: "کوره القایی پیش‌گرم (فورج) ",
    category: "FORGING_FURNACE" as const,
    description:
      "کوره‌های القایی پیش‌گرم (فورج) ساخت شرکت کوره القایی پارسیان پرتوالوند بر اساس سفارش مشتری، توان مورد نیاز و نوع کاربری طراحی و ساخته می‌شوند. این کوره‌ها با دانش روز و سال‌ها تجربه، قطعات فلزی رو تا دمای مشخص پیش‌گرم می‌کنند تا آماده عملیات فورج شوند. مزایای اصلی: اپراتوری بسیار ساده، عدم ایجاد اکسید روی قطعه به دلیل زمان کوتاه حرارت‌دهی، شروع به کار سریع، راندمان بالا، کنترل دقیق دما، اشغال فضای کمتر و قابلیت اتوماسیون با خط تولید.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [
      // فولاد ۱۲۰۰°C
      {
        powerKw: 100,
        kgHr: 300,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },
      {
        powerKw: 150,
        kgHr: 400,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },
      {
        powerKw: 250,
        kgHr: 700,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },
      {
        powerKw: 350,
        kgHr: 1100,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },
      {
        powerKw: 500,
        kgHr: 1500,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },
      {
        powerKw: 600,
        kgHr: 1800,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },
      {
        powerKw: 1000,
        kgHr: 3000,
        temperature: 1200,
        metal: "STEEL",
        diameterMm: 50,
      },

      // برنج ۷۵۰°C
      {
        powerKw: 100,
        kgHr: 600,
        temperature: 750,
        metal: "BRASS",
        diameterMm: 50,
      },
      {
        powerKw: 150,
        kgHr: 900,
        temperature: 750,
        metal: "BRASS",
        diameterMm: 50,
      },
      {
        powerKw: 250,
        kgHr: 1450,
        temperature: 750,
        metal: "BRASS",
        diameterMm: 50,
      },
      {
        powerKw: 350,
        kgHr: 2000,
        temperature: 750,
        metal: "BRASS",
        diameterMm: 50,
      },
      {
        powerKw: 500,
        kgHr: 2900,
        temperature: 750,
        metal: "BRASS",
        diameterMm: 50,
      },
    ],
    components: [
      {
        title: "سیستم خنک‌کننده",
        description:
          "شامل مبدل حرارتی، قطره‌گیر برج خنک‌کننده، الکتروپمپ‌ها، فن، بدنه گالوانیزه و سختی‌گیر مغناطیسی.",
      },
      {
        title: "سیستم مبدل فرکانس",
        description:
          "تابلو مبدل فرکانس مجهز به PLC و HMI برای کنترل دقیق و ساده تمام بخش‌ها.",
      },
      {
        title: "کویل و میزکار",
        description:
          "طراحی شده بر اساس قطر و نوع قطعه کار برای حداکثر راندمان پیش‌گرم.",
      },
    ],
    images: [
      "/images/products/forging-furnace1.webp",
      "/images/products/forging-furnace2.webp",
      "/images/products/forging-furnace3.webp",
      "/images/products/forging-furnace4.webp",
    ],
    featured: false,
    order: 2,
  },
  {
    slug: "forming-furnace",
    name: "کوره القایی فورمینگ",
    category: "FORMING_FURNACE" as const,
    description:
      "کوره‌های القایی فورمینگ پارسیان برای گرم کردن موضعی یا کامل قطعات قبل از عملیات شکل‌دهی و فرمینگ طراحی شدند. این کوره‌ها با کنترل دقیق دما و راندمان بالا، امکان تولید قطعات با کیفیت یکنواخت در خط تولید انبوه رو فراهم می‌کنند و فضای کمتری نسبت به کوره‌های سنتی اشغال می‌کنند",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [
      {
        title: "سیستم خنک‌کننده",
        description:
          "شامل مبدل حرارتی، قطره‌گیر برج خنک‌کننده، الکتروپمپ‌ها، فن، بدنه گالوانیزه و سختی‌گیر مغناطیسی.",
      },
      {
        title: "سیستم مبدل فرکانس",
        description:
          "تابلو مبدل فرکانس مجهز به PLC و HMI برای کنترل دقیق و ساده تمام بخش‌ها.",
      },
      {
        title: "کویل ",
        description:
          "طراحی شده بر اساس قطر و نوع قطعه کار برای حداکثر راندمان پیش‌گرم.",
      },
    ],
    images: [
      "/images/products/forming-furnace-1.webp",
      "/images/products/forming-furnace-2.webp",
    ],
    featured: false,
    order: 4,
  },
  {
    slug: "hardening-furnace",
    name: "کوره القایی سخت‌کاری",
    category: "HARDENING_FURNACE" as const,
    description:
      "کوره‌های سخت‌کاری القایی پارسیان در رنج فرکانس متوسط (MF) تولید می‌شوند. عملیات سخت‌کاری القایی یکی از شاخه‌های مهم متالورژی است که به دلیل تغییر خواص فیزیکی و افزایش راندمان قطعات، در بسیاری از صنایع استفاده می‌شود. این کوره‌ها قابلیت کنترل دقیق دما و عمق نفوذ سخت‌کاری را دارند و برای قطعاتی مثل محورها، یاتاقان‌ها، میل‌بادامک، پین‌ها، پیستون‌ها، چرخ‌دنده‌ها، شفت‌ها و میل‌لنگ موتور مناسب هستند.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [
      {
        powerKw: 100,
        frequencyRange: "MF",
        workFrequencyKHz: "7-15",
        type: "MF",
      },
      {
        powerKw: 100,
        frequencyRange: "MF",
        workFrequencyKHz: "7-9",
        type: "MF",
      },
      {
        powerKw: 150,
        frequencyRange: "MF",
        workFrequencyKHz: "7-9",
        type: "MF",
      },
      {
        powerKw: 150,
        frequencyRange: "MF",
        workFrequencyKHz: "2-3",
        type: "MF",
      },
      {
        powerKw: 250,
        frequencyRange: "MF",
        workFrequencyKHz: "2-3",
        type: "MF",
      },
      {
        powerKw: 500,
        frequencyRange: "MF",
        workFrequencyKHz: "1-2",
        type: "MF",
      },
    ],
    components: [
      {
        title: "سیستم کنترل هوشمند",
        description:
          "کنترل توان از طریق مانیتور HMI، تنظیم سرعت خطی و دورانی، برنامه‌ریزی و زمان‌بندی عملیات کوئنچ، مانیتورینگ موقعیت اینداکتور.",
      },
      {
        title: "سیستم مبدل فرکانس",
        description: "قابلیت تولید در رنج MF  با کنترل دقیق عمق سخت‌کاری.",
      },
    ],
    images: [
      "/images/products/hardening-furnace1.webp",
      "/images/products/hardening-furnace2.webp",
      "/images/products/hardening-furnace3.webp",
      "/images/products/hardening-furnace4.webp",
    ],
    featured: false,
    order: 3,
  },
  // ========== لوازم یدکی (SPARE_PARTS) ==========
  {
    slug: "phase-control-thyristor",
    name: "تریستور کنترل فاز",
    category: "SPARE_PARTS" as const,
    subCategory: "thyristor",
    description:
      "تریستور کنترل فاز با تحمل جریان و ولتاژ بالا، مناسب تابلوهای مبدل فرکانس کوره‌های القایی. عملکرد پایدار و طول عمر بالا.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 10,
  },
  {
    slug: "fast-turnoff-thyristor",
    name: "تریستور Fast Turn-off",
    category: "SPARE_PARTS" as const,
    subCategory: "thyristor",
    description:
      "تریستور Fast Turn-off با زمان خاموشی کوتاه، مناسب مدارهای قدرت کوره‌های القایی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 11,
  },
  {
    slug: "high-frequency-thyristor",
    name: "تریستور High Frequency",
    category: "SPARE_PARTS" as const,
    subCategory: "thyristor",
    description:
      "تریستور فرکانس بالا مناسب کوره‌های القایی فرکانس متوسط و بالا.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 12,
  },
  {
    slug: "disc-thyristor",
    name: "تریستور دیسکی",
    category: "SPARE_PARTS" as const,
    subCategory: "thyristor",
    description:
      "تریستور دیسکی (کپسولی) با تحمل جریان بسیار بالا برای کوره‌های صنعتی سنگین.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 13,
  },
  {
    slug: "rectifier-diode",
    name: "دیود یکسوساز",
    category: "SPARE_PARTS" as const,
    subCategory: "diode",
    description:
      "دیود یکسوساز قدرت برای مدارهای یکسوسازی تابلوهای مبدل فرکانس کوره‌های القایی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 14,
  },
  {
    slug: "fast-recovery-diode",
    name: "دیود Fast Recovery",
    category: "SPARE_PARTS" as const,
    subCategory: "diode",
    description:
      "دیود Fast Recovery با زمان بازیابی سریع برای مدارهای حفاظتی و یکسوسازی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 15,
  },
  {
    slug: "thyristor-module",
    name: "ماژول تریستوری",
    category: "SPARE_PARTS" as const,
    subCategory: "module",
    description: "ماژول تریستوری آماده نصب با طراحی فشرده و تحمل جریان بالا.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 16,
  },
  {
    slug: "diode-module",
    name: "ماژول دیودی",
    category: "SPARE_PARTS" as const,
    subCategory: "module",
    description: "ماژول دیودی قدرت مناسب مدارهای یکسوسازی و پل دیودی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 17,
  },
  {
    slug: "igbt-module",
    name: "IGBT و ماژول IGBT",
    category: "SPARE_PARTS" as const,
    subCategory: "igbt",
    description: "IGBT و ماژول IGBT صنعتی برای اینورترهای کوره‌های القایی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 18,
  },
  {
    slug: "water-cooled-capacitor",
    name: "خازن آب‌خنک قدرت",
    category: "SPARE_PARTS" as const,
    subCategory: "capacitor",
    description:
      "خازن آب‌خنک قدرت با تحمل جریان بالا برای بانک خازن کوره‌های القایی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 19,
  },
  {
    slug: "snubber-capacitor",
    name: "خازن اسنابر",
    category: "SPARE_PARTS" as const,
    subCategory: "capacitor",
    description: "خازن اسنابر برای محافظت از تریستورها و کاهش تنش ولتاژ.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 20,
  },
  {
    slug: "control-board",
    name: "برد کنترل و درایور",
    category: "SPARE_PARTS" as const,
    subCategory: "board",
    description:
      "برد کنترل و درایور اختصاصی پارسیان، سازگار با تابلوهای مبدل فرکانس.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 21,
  },
  {
    slug: "copper-coil",
    name: "کویل مسی",
    category: "SPARE_PARTS" as const,
    subCategory: "coil",
    description:
      "کویل مسی با خلوص بالا و طراحی دقیق بر اساس توان و فرکانس کوره.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 22,
  },
  {
    slug: "insulation-materials",
    name: "مواد عایق‌کاری کویل",
    category: "SPARE_PARTS" as const,
    subCategory: "coil",
    description:
      "میکا، نوار سیلیکونی و اسپیسر مقاوم در برابر حرارت و جریان القایی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 23,
  },
  {
    slug: "yoke",
    name: "یوک لایه‌ای",
    category: "SPARE_PARTS" as const,
    subCategory: "coil",
    description: "یوک لایه‌ای سیلیکونی برای کاهش تلفات هسته و بهبود راندمان.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 24,
  },
  {
    slug: "dc-choke",
    name: "دی‌سی چوک",
    category: "SPARE_PARTS" as const,
    subCategory: "board",
    description: "چوک جریان مستقیم برای فیلتر کردن ریپل جریان در مدار قدرت.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 25,
  },

  // ========== تجهیزات جانبی (PERIPHERAL_EQUIPMENT) ==========
  {
    slug: "heatsink",
    name: "هیت‌سینک",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cooling",
    description:
      "هیت‌سینک مسی و آلومینیومی برای خنک‌کاری تریستور، دیود و IGBT.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 30,
  },
  {
    slug: "carbon-free-hose",
    name: "شیلنگ بدون کربن",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cooling",
    description: "شیلنگ آب‌گرد بدون کربن مقاوم در برابر حرارت و فشار.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 31,
  },
  {
    slug: "water-pump",
    name: "پمپ آب خنک‌کننده",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cooling",
    description: "الکتروپمپ صنعتی مخصوص مدار بسته خنک‌کننده کوره‌های القایی.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 32,
  },
  {
    slug: "cooling-tower-parts",
    name: "قطعات برج خنک‌کننده",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cooling",
    description: "مبدل حرارتی، قطره‌گیر، فن و بدنه گالوانیزه برج خنک‌کننده.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 33,
  },
  {
    slug: "magnetic-hardener",
    name: "سختی‌گیر مغناطیسی",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cooling",
    description: "سختی‌گیر مغناطیسی برای جلوگیری از رسوب در مدار آب خنک‌کننده.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 34,
  },
  {
    slug: "water-cooled-cable",
    name: "کابل آب‌خنک",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cable",
    description: "کابل قدرت آب‌خنک برای انتقال ایمن جریان بین تابلو و کویل.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 35,
  },
  {
    slug: "power-link",
    name: "لینک قدرت و اتصالات",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "cable",
    description: "لینک قدرت و اتصالات استاندارد با کیفیت بالا.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 36,
  },
  {
    slug: "current-transformer",
    name: "ترانس جریان (C.T)",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "control",
    description: "ترانس جریان دقیق برای اندازه‌گیری و حفاظت مدار قدرت.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 37,
  },
  {
    slug: "hmi-plc",
    name: "تابلو کنترل HMI و PLC",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "control",
    description:
      "تابلو کنترل مجهز به HMI و PLC برای کنترل دقیق پارامترهای کوره.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 38,
  },
  {
    slug: "crucible-body",
    name: "بدنه بوته",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "crucible",
    description: "بدنه بوته در انواع آلومینیومی، فولادی و استیل.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 39,
  },
  {
    slug: "hydraulic-parts",
    name: "تجهیزات هیدرولیک",
    category: "PERIPHERAL_EQUIPMENT" as const,
    subCategory: "hydraulic",
    description: "سیلندر، پمپ و شیرآلات سیستم تیلت و جابجایی بوته.",
    capacityKg: null,
    powerKw: null,
    frequencyHz: null,
    variants: [],
    components: [],
    images: [],
    featured: false,
    order: 40,
  },
];
async function main() {
  await prisma.product.deleteMany({
    where: { slug: { in: staleProductSlugs } },
  });

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
